apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: red
spec:
  containers:
  - name: red
    image: redis
  initContainers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 20']