apiVersion: v1
kind: Pod
metadata:
  name: webapp-color

spec:
  containers:
  - name: webapp-color
    image: nginx:alpine
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
          name: webapp-config-map