apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
  namespace: haproxy-controller-devops
rules:
- apiGroups: [""]
  resources: ["nodes","services", "endpoints", "pods","secrets","namespaces","events","serviceaccounts","Configmaps"]
  verbs: ["get", "list", "watch","create", "patch", "update"]